name: Build FrankenPHP Binary with PHP 8.3 & Laravel Extensions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      PHP_VERSION: "8.3"
      PHP_EXTENSIONS: "pdo_mysql,mbstring,xml,ctype,json,openssl,bcmath,fileinfo"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build static binary
        run: |
          chmod +x build-static.sh
          ./build-static.sh

      - name: Upload FrankenPHP binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: frankenphp-binary
          path: frankenphp
